apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  sources:
    - repoURL: https://github.com/rathix/k8s-prd.git
      targetRevision: HEAD
      path: kube-vip
    - repoURL: https://github.com/rathix/k8s-prd.git
      targetRevision: HEAD
      path: traefik
    - repoURL: https://github.com/rathix/k8s-prd.git
      targetRevision: HEAD
      path: actualbudget
    - repoURL: https://github.com/rathix/k8s-prd.git
      targetRevision: HEAD
      path: servarr
