apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.34.0
      helm:
        releaseName: pihole
        valuesObject:
          persistentVolumeClaim:
            enabled: true

          ingress:
            enabled: true
            hosts: ["pihole.kennyandries.com"]

        serviceDns:
          loadBalancerIP: 192.168.1.3
          loadBalancerClass: kube-vip.io/kube-vip-class
          type: LoadBalancer
