apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-jellyfin-media-nfs
  namespace: servarr
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hpool/media
    server: pkb-nas-tns-1
