apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-jellyfin-media
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ""
  volumeName: servarr-jellyfin-media-nfs
