---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBcWsPhnz7ZVJqYsrPkHdxPoyx1g1a4Q+Irvb0izRzuuDCTPvwnddZd2VD1bINe3YzwWY6zgvHbHpCCUfJnS1TuFXRfMv0zgIIhSsKXgmtngM8II+CnfimRAJrKZHnvof/IpcQeEznyeRUZjFPH/h5to+L10kir2MWSajp4ovqu0oNwGSO7f9yNvUi+PtSxQ7QdovVth0rgofM1Is0QE38vgimkdYUrfft/1wJowWK87NSiCiTRjDBFs5gGCe2QwxDGVFrUQc4Xjmx56yrxj0Xv2oxkLj6nLFNe0hMnKJXsdsjP0sv2z5rUNyBH3Sd+4zNIOUmv/WZdSo+gb8jf2iwlQazjFWnJzHCoxi0eo/9dXmLBKTrqhx+v18bLlI4b+KPo3IlXcjGDKsfh/pTZj9nzIzTW16CEWRvmK3rtUdHiXYF/o9B1VXOyUdoO5l2jtR87MAB83mpaeyziQ5IaAXn3Gp6yJcW9DNsyAkQj7yc/Jy5tu2cumYB7g4QIxmFBr9cLiGOBFp9UkWIuWWsx8cNcnY8Fkzd4wAjaN/lhxdub99nl4zVZYkk7rBREfTuy3acLC+2qLRR0STHDlqmylZTeIeTahKiVezfp+9x+dzlVtXDT9Zc/YGWWL1DHp032ICd/K80VfFc+N7D9SGQ4Kcm1ZsScXvovGB5zgJitKwPht5xoWuctLBarTyDIMRS0kPZ30oJdVYv34mWwdobEwbQUaLlYjmmkpgpTQMBOp7KnrA==
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque
