apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  sources:
    - repoURL: https://github.com/rathix/k8s-prd.git
      targetRevision: HEAD
      path: cert-manager/manifests
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.19.1
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
    - repoURL: https://vadimkim.github.io/cert-manager-webhook-hetzner
      chart: cert-manager-webhook-hetzner
      targetRevision: v1.4.0
      helm:
        releaseName: cert-manager-webhook-hetzner
